version: "3.6"
services:
    proxy: 
        image: nginx:latest
        restart: always
        volumes:
            - ./public:/var/www/html
            - /data/blog:/var/www/blog
            - ./conf.d:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data-redmine:/var/www/certbot-redmine
            - ./certbot/data-blog:/var/www/certbot-blog
            - ./certbot/data-default:/var/www/certbot-default
            - ./certbot/data-geodiscovery-cloud:/var/www/certbot-geodiscovery-cloud
        ports:
            - 80:80
            - 443:443

    cert_redmine:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email stefan.langenmaier@gmail.com --agree-tos --no-eff-email -d redmine.up-log.de
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data-redmine:/var/www/certbot

    cert_blog:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email stefan.langenmaier@gmail.com --agree-tos --no-eff-email -d blog.up-log.de
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data-blog:/var/www/certbot

    cert_default:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email stefan.langenmaier@gmail.com --agree-tos --no-eff-email -d up-log.de
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data-default:/var/www/certbot

    cert_geodiscovery_cloud:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email stefan.langenmaier@gmail.com --agree-tos --no-eff-email -d cloud.geodiscovery.xn--rro-pla.de
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data-geodiscovery-cloud:/var/www/certbot

networks:
  default:
    external:
      name: proxy
